AlgorithmsEvaluationPerformanceApp/Models/BenchmarkModel.cs
namespace AlgorithmsEvaluationPerformanceApp.Models
{
    public class BenchmarkModel
    {
        public string UserCode { get; set; }
        public int[] BenchmarkSizeParams { get; set; }
    }
}

AlgorithmsEvaluationPerformanceApp/Models/ErrorViewModel.cs
namespace AlgorithmsEvaluationPerformanceApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlgorithmsEvaluationPerformanceApp/Controllers/HomeController.cs
using AlgorithmsEvaluationPerformanceApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AlgorithmsEvaluationPerformanceApp.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlgorithmsEvaluationPerformanceApp/Controllers/UserCodeController.cs
using AlgorithmsEvaluationPerformanceApp.Models;
using AlgorithmsEvaluationPerformanceApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AlgorithmsEvaluationPerformanceApp.Controllers
{
    public class UserCodeController : Controller
    {
        List<int> PossibleSizes = new() { 10, 100, 1000, 10_000, 100_000, 1_000_000, 10_000_000 };

        public UserCodeController()
        {
            
        }


        [HttpGet]
        public IActionResult Run()
        {
            var model = new BenchmarkModel();

            var selectListItems = PossibleSizes.Select(pv => new SelectListItem
            {
                Value = pv.ToString(),
                Text = pv.ToString()
            }).ToList();

            model.BenchmarkSizeParams = PossibleSizes.ToArray();

            ViewBag.PossibleValues = selectListItems;

            return View(model);
        }

        [HttpPost]
        public IActionResult Run(BenchmarkModel model)
        {
            ViewData["UserInput"] = model.UserCode;

            var finalCode = CodeTemplateService.GetBenchmarkCode(model.UserCode, model.BenchmarkSizeParams);
            FileService.SaveConsoleProjectBenchmarkFile(finalCode);
            ApplicationService.RunDotNetConsoleProject();

            string reportPath;

            while (true)
            {
                reportPath = BenchmarkReportService.GetReportPath();
                if (reportPath != string.Empty)
                {
                    break;
                }
                Task.Delay(3000); // Ждем 3 секунду перед повторной проверкой
            }

            return PhysicalFile(reportPath, "text/html");
        }
    }
}

AlgorithmsEvaluationPerformanceApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AlgorithmsEvaluationPerformanceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlgorithmsEvaluationPerformanceApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlgorithmsEvaluationPerformanceApp.styles.css" asp-append-version="true" />
    <link href="~/css/site.css" type="text/css" rel="stylesheet" />

    <style>
        a.navbar-brand {
            white-space: normal;
            text-align: center;
            word-break: break-all;
        }

        a {
            color: #0077cc;
        }

        .btn-primary {
            color: #fff;
            background-color: #1b6ec2;
            border-color: #1861ac;
        }

        .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
            color: #fff;
            background-color: #1b6ec2;
            border-color: #1861ac;
        }

        .border-top {
            border-top: 1px solid #e5e5e5;
        }

        .border-bottom {
            border-bottom: 1px solid #e5e5e5;
        }

        .box-shadow {
            box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
        }

        button.accept-policy {
            font-size: 1rem;
            line-height: inherit;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            white-space: nowrap;
            line-height: 60px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AlgorithmsEvaluationPerformanceApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AlgorithmsEvaluationPerformanceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <!-- and it's easy to individually load additional languages -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/go.min.js"></script>
    <script>hljs.highlightAll();</script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AlgorithmsEvaluationPerformanceApp/Views/UserCode/Run.cshtml
@model BenchmarkModel

<style>
    .wide-input {
        width: 100%;
        height: 165px;
    }

    body {
        font-family: Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        padding: 20px;
    }

    p {
        margin-bottom: 10px;
    }

</style>

<div class="alert alert-success" role="alert">
    Это приложение предназначено для тестирования производительности различных алгоритмов сортировки, поиска на массивах разных размеров.
</div>

<div class="alert alert-success" role="alert">
    Для вашего алгоритма будет создан бенчмарк. Тестирование будет запущено на массивах с выбранными размерами от
    <span class="badge text-bg-secondary bg-secondary">10</span>
    до
    <span class="badge text-bg-secondary bg-secondary">10 000 000 </span>
    элементов.
</div>


<div class="alert alert-success" role="alert">
    Представленный алгоритм должен в основе своей работать с массивом состоящем из чисел
    <span class="badge text-bg-secondary bg-primary">int</span>.
    Представьте ваш код на языке
    <span class="badge text-bg-secondary bg-success">C#</span>
    в виде метода.
</div>

<pre><code class="language-csharp">
public void MethodName()
{
   // учитывайте, что изначальный массив должен носить название - _sourceArray
}
</code></pre>
<p>
    Пожалуйста, убедитесь, что ваш код корректно обрабатывает все возможные случаи и не содержит ошибок.
    <br>Все предоставленные алгоритмы должны быть способны сортировать массивы любого размера без ошибок.
    <br>Результаты тестов будут представлены в виде таблицы.
</p>

<p>Выберите размеры массивов</p>
<form id="benchmarkForm" asp-controller="UserCode" asp-action="Run" method="post">
    <select asp-for="BenchmarkSizeParams" asp-items="ViewBag.PossibleValues" multiple class="select"></select>
    <textarea asp-for="UserCode" class="wide-input-for-code"></textarea>
    <p><hr /></p>
    <button class="glow-on-hover" type="submit"> Запустить бенчмарк </button>
</form>


<!--
<script>
    $(document).ready(function () {
        $('.select').select2({
            placeholder: "Выберите опцию",
            allowClear: true
        });
    });
</script>
-->



<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<p><hr /></p>

<pre class="wide-input">
<code class="language-csharp" id="highlightedUserCode">@ViewData["UserInput"]</code> 
</pre>

<div class="loader-wrapper" style="display: none">
    <span class="loader"></span>
</div>

<script>
    $(document).ready(function () {
        $('#benchmarkForm').submit(function (e) {
            const loadWrapper = $('.loader-wrapper')
            console.log(loadWrapper)
            $('.loader-wrapper').show();
        });
    });
</script>